[allergy_types.drug]
label = "Drug"
enabled = true

[allergy_types.food]
label = "Food"
enabled = true

[allergy_types.environmental]
label = "Environmental"
enabled = true

[allergy_types.other]
label = "Other"
enabled = true

[severities.mild]
label = "Mild"
enabled = true

[severities.moderate]
label = "Moderate"
enabled = true

[severities.severe]
label = "Severe"
enabled = true
