use chrono::{DateTime, Duration, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use super::model::{AppointmentStatus, AppointmentType};

/// Data transfer object for creating a new appointment
///
/// Used when a user wants to schedule a new appointment.
/// The ID, timestamps, and audit fields are generated by the system.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NewAppointmentData {
    /// Patient being scheduled for appointment
    pub patient_id: Uuid,

    /// Practitioner conducting the appointment
    pub practitioner_id: Uuid,

    /// Appointment start date and time
    pub start_time: DateTime<Utc>,

    /// Duration of appointment (used to calculate end_time)
    pub duration: Duration,

    /// Type of appointment
    pub appointment_type: AppointmentType,

    /// Reason for visit (optional)
    pub reason: Option<String>,

    /// Is this an emergency/urgent appointment?
    #[serde(default)]
    pub is_urgent: bool,
}

/// Data transfer object for updating an existing appointment
///
/// All fields are optional - only provided fields will be updated.
/// Audit fields (created_at, updated_at, created_by, updated_by) are managed by the system.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UpdateAppointmentData {
    /// Update appointment status
    pub status: Option<AppointmentStatus>,

    /// Update appointment type
    pub appointment_type: Option<AppointmentType>,

    /// Update reason for visit
    pub reason: Option<String>,

    /// Update internal notes
    pub notes: Option<String>,

    /// Update urgent flag
    pub is_urgent: Option<bool>,

    /// Update confirmation status
    pub confirmed: Option<bool>,

    /// Update reminder sent flag
    pub reminder_sent: Option<bool>,

    /// Update cancellation reason (used when status is Cancelled)
    pub cancellation_reason: Option<String>,
}

/// Data transfer object for searching and filtering appointments
///
/// All fields are optional - only provided fields are used in the search.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AppointmentSearchCriteria {
    /// Filter by patient ID
    pub patient_id: Option<Uuid>,

    /// Filter by practitioner ID
    pub practitioner_id: Option<Uuid>,

    /// Filter appointments from this date onwards
    pub date_from: Option<DateTime<Utc>>,

    /// Filter appointments up to this date
    pub date_to: Option<DateTime<Utc>>,

    /// Filter by appointment status
    pub status: Option<AppointmentStatus>,

    /// Filter by appointment type
    pub appointment_type: Option<AppointmentType>,

    /// Filter by urgent flag
    pub is_urgent: Option<bool>,

    /// Filter by confirmation status
    pub confirmed: Option<bool>,
}

/// Calendar view for a specific day showing all practitioners and appointments
///
/// Used by the calendar UI to display a day's schedule across multiple practitioners.
/// Contains all appointments organized by practitioner for efficient rendering.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarDayView {
    /// The date being displayed
    pub date: chrono::NaiveDate,

    /// List of practitioners with their schedules for this day
    pub practitioners: Vec<PractitionerSchedule>,
}

/// Schedule for a single practitioner on a specific day
///
/// Groups all appointments for one practitioner, making it easy to
/// render a practitioner's column in the calendar view.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PractitionerSchedule {
    /// Practitioner unique identifier
    pub practitioner_id: Uuid,

    /// Practitioner display name (e.g., "Dr. Smith")
    pub practitioner_name: String,

    /// All appointments for this practitioner on this day
    pub appointments: Vec<CalendarAppointment>,
}

/// Simplified appointment for calendar display
///
/// Contains only the essential fields needed to render an appointment
/// in the calendar grid. Patient name is denormalized for performance.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarAppointment {
    /// Appointment unique identifier
    pub id: Uuid,

    /// Patient unique identifier
    pub patient_id: Uuid,

    /// Patient display name (denormalized for performance)
    pub patient_name: String,

    /// Practitioner unique identifier (needed for calendar filtering)
    pub practitioner_id: Uuid,

    /// Appointment start time
    pub start_time: DateTime<Utc>,

    /// Appointment end time
    pub end_time: DateTime<Utc>,

    /// Type of appointment (Standard, LongConsultation, etc.)
    pub appointment_type: AppointmentType,

    /// Current status (Scheduled, CheckedIn, etc.)
    pub status: AppointmentStatus,

    /// Whether this is an urgent appointment
    #[serde(default)]
    pub is_urgent: bool,

    /// Number of 15-minute slots this appointment spans (for rendering)
    pub slot_span: u8,

    /// Reason for visit (optional, for modal display)
    pub reason: Option<String>,

    /// Internal notes (optional, for modal display)
    pub notes: Option<String>,
}

impl CalendarAppointment {
    /// Calculate duration in minutes
    pub fn duration_minutes(&self) -> i64 {
        (self.end_time - self.start_time).num_minutes()
    }
}
