use chrono::{DateTime, Duration, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use super::model::{AppointmentStatus, AppointmentType};

/// Data transfer object for creating a new appointment
///
/// Used when a user wants to schedule a new appointment.
/// The ID, timestamps, and audit fields are generated by the system.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NewAppointmentData {
    /// Patient being scheduled for appointment
    pub patient_id: Uuid,

    /// Practitioner conducting the appointment
    pub practitioner_id: Uuid,

    /// Appointment start date and time
    pub start_time: DateTime<Utc>,

    /// Duration of appointment (used to calculate end_time)
    pub duration: Duration,

    /// Type of appointment
    pub appointment_type: AppointmentType,

    /// Reason for visit (optional)
    pub reason: Option<String>,

    /// Is this an emergency/urgent appointment?
    #[serde(default)]
    pub is_urgent: bool,
}

/// Data transfer object for updating an existing appointment
///
/// All fields are optional - only provided fields will be updated.
/// Audit fields (created_at, updated_at, created_by, updated_by) are managed by the system.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UpdateAppointmentData {
    /// Update appointment status
    pub status: Option<AppointmentStatus>,

    /// Update appointment type
    pub appointment_type: Option<AppointmentType>,

    /// Update reason for visit
    pub reason: Option<String>,

    /// Update internal notes
    pub notes: Option<String>,

    /// Update urgent flag
    pub is_urgent: Option<bool>,

    /// Update confirmation status
    pub confirmed: Option<bool>,

    /// Update reminder sent flag
    pub reminder_sent: Option<bool>,

    /// Update cancellation reason (used when status is Cancelled)
    pub cancellation_reason: Option<String>,
}

/// Data transfer object for searching and filtering appointments
///
/// All fields are optional - only provided fields are used in the search.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AppointmentSearchCriteria {
    /// Filter by patient ID
    pub patient_id: Option<Uuid>,

    /// Filter by practitioner ID
    pub practitioner_id: Option<Uuid>,

    /// Filter appointments from this date onwards
    pub date_from: Option<DateTime<Utc>>,

    /// Filter appointments up to this date
    pub date_to: Option<DateTime<Utc>>,

    /// Filter by appointment status
    pub status: Option<AppointmentStatus>,

    /// Filter by appointment type
    pub appointment_type: Option<AppointmentType>,

    /// Filter by urgent flag
    pub is_urgent: Option<bool>,

    /// Filter by confirmation status
    pub confirmed: Option<bool>,
}
