pub mod api;
pub mod appointment;
pub mod audit;
#[cfg(feature = "billing")]
pub mod billing;
pub mod clinical;
pub mod error;
#[cfg(feature = "immunisation")]
pub mod immunisation;
pub mod macros;
#[cfg(feature = "pathology")]
pub mod pathology;
pub mod patient;
#[cfg(feature = "prescription")]
pub mod prescription;
#[cfg(feature = "referral")]
pub mod referral;
pub mod user;
